export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  OPERATOR = 'OPERATOR',
  DRIVER = 'DRIVER',
  PASSENGER = 'PASSENGER',
}

export enum TripStatus {
  SCHEDULED = 'SCHEDULED',
  BOARDING = 'BOARDING',
  DEPARTED = 'DEPARTED',
  IN_TRANSIT = 'IN_TRANSIT',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum SeatStatus {
  AVAILABLE = 'AVAILABLE',
  SELECTED = 'SELECTED',
  RESERVED = 'RESERVED',
  BOOKED = 'BOOKED',
  BLOCKED = 'BLOCKED',
}

export enum BookingStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
  REFUNDED = 'REFUNDED',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  PAID = 'PAID',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  CANCELLED = 'CANCELLED',
}

export enum TicketStatus {
  ISSUED = 'ISSUED',
  USED = 'USED',
  CANCELLED = 'CANCELLED',
}

export enum VehicleType {
  BUS = 'Bus',
  MINIBUS = 'Minibus',
  COACH = 'Coach',
  OTHER = 'Other',
}

export enum NotificationType {
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  TRIP_REMINDER = 'TRIP_REMINDER',
  TRIP_CHANGED = 'TRIP_CHANGED',
  TRIP_CANCELLED = 'TRIP_CANCELLED',
  REFUND_PROCESSED = 'REFUND_PROCESSED',
  BOARDING_REMINDER = 'BOARDING_REMINDER',
}
